# Get all employees
GET http://localhost:8080/employees

###
# Get a specific employee
GET http://localhost:8080/departments/d6d04eb8-83e8-47bb-af10-393b457499f3/employees/d6d04eb8-83e8-47bb-af10-393b457499f3