# Get all employees
GET http://localhost:8080/employees

###
# Add an employee
POST http://localhost:8080/employees
Content-Type: application/json

{
    "vaccinationStatus": 2,
    "vaccinationBrand": 2,
    "healthStatus": 1,
    "employeeVaccinations": null
}

###
# Delete an employee
DELETE http://localhost:8080/employees/97a59744-ad57-4de7-ba87-0bf00c618c36
Content-Type: application/json