# Get all employees
GET http://localhost:8080/employees

###
# Add an employee
POST http://localhost:8080/employees
Content-Type: application/json

{
    "vaccinationStatus": 2,
    "vaccinationBrand": 2,
    "healthStatus": 1,
    "employeeVaccinations": null
}