# Get all employees
GET http://localhost:8080/employees

###
# Add an employee
POST http://localhost:8080/employees
Content-Type: application/json

{
    "vaccinationStatus": 2,
    "vaccinationBrand": 2,
    "healthStatus": 1,
    "employeeVaccinations": null
}

###
# Delete an employee
DELETE http://localhost:8080/employees/a5a256f1-eea7-4a63-a3ff-9fdbd360a670
Content-Type: application/json